spring:
  application:
    name: vacanceLog

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 1500
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ap-northeast-2
      stack:
        auto: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    persistAuthorization: true
  override-with-generic-response: false

